In [334]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score

from tensorflow import keras
import tensorflow as tf
from keras.layers import *
from keras import backend as K

In [335]:
df = pd.read_csv('../Resultados/df_train.csv')

In [336]:
y = df['rating_num']
X = df.drop(['rating_num', 'row_id'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=7)

In [337]:
def coeff_determination(y_true, y_pred):
    SS_res =  K.sum(K.square( y_true-y_pred )) 
    SS_tot = K.sum(K.square( y_true - K.mean(y_true) ) ) 
    return ( 1 - SS_res/(SS_tot + K.epsilon()) )

In [338]:
model = keras.Sequential()
model.add(Dense(64, input_dim=450, activation='tanh')) #ok 64 - bom, 32 -ruim, 128-quase bom 100 ruim
# model.add(Dropout(.2))
model.add(Dense(20, activation='relu')) #32 ->2.10, 64 ->2.9 20->1.8, 10-.3.6 tanh uma merda
# model.add(Dropout(.2))
# model.add(Dense(16, activation='relu'))
model.add(Dense(1))

In [339]:
model.summary()

Model: "sequential_31"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_67 (Dense)            (None, 64)                28864

 dense_68 (Dense)            (None, 20)                1300

 dense_69 (Dense)            (None, 1)                 21

=================================================================
Total params: 30,185
Trainable params: 30,185
Non-trainable params: 0
_________________________________________________________________

In [340]:
opt = keras.optimizers.Nadam(learning_rate=0.005) #0.001 e 0.01-pior 0.005 - melhor 0.005 - ok
model.compile(optimizer= opt, loss='mse', metrics=['mse'])#coeff_determination
history = model.fit(X_train, y_train, epochs=50, verbose=1)

Epoch 1/50
395/395 [==============================] - 5s 6ms/step - loss: 3.5382 - mse: 3.5382
Epoch 2/50
395/395 [==============================] - 2s 5ms/step - loss: 3.0886 - mse: 3.0886
Epoch 3/50
395/395 [==============================] - 2s 6ms/step - loss: 3.0175 - mse: 3.0175
Epoch 4/50
395/395 [==============================] - 2s 5ms/step - loss: 2.9996 - mse: 2.9996
Epoch 5/50
395/395 [==============================] - 2s 5ms/step - loss: 2.9705 - mse: 2.9705
Epoch 6/50
395/395 [==============================] - 2s 5ms/step - loss: 2.9599 - mse: 2.9599
Epoch 7/50
395/395 [==============================] - 2s 5ms/step - loss: 2.9482 - mse: 2.9482
Epoch 8/50
395/395 [==============================] - 2s 6ms/step - loss: 2.9225 - mse: 2.9225
Epoch 9/50
395/395 [==============================] - 2s 5ms/step - loss: 2.8997 - mse: 2.8997
Epoch 10/50
395/395 [==============================] - 2s 5ms/step - loss: 2.9212 - mse: 2.9212
Epoch 11/50
395/395 [==============================] - 2s 5ms/step - loss: 2.9037 - mse: 2.9037
Epoch 12/50
395/395 [==============================] - 2s 5ms/step - loss: 2.8837 - mse: 2.8837
Epoch 13/50
395/395 [==============================] - 2s 5ms/step - loss: 2.8981 - mse: 2.8981
Epoch 14/50
395/395 [==============================] - 2s 5ms/step - loss: 2.8808 - mse: 2.8808
Epoch 15/50
395/395 [==============================] - 2s 5ms/step - loss: 2.8635 - mse: 2.8635
Epoch 16/50
395/395 [==============================] - 3s 7ms/step - loss: 2.8718 - mse: 2.8718
Epoch 17/50
395/395 [==============================] - 2s 5ms/step - loss: 2.8362 - mse: 2.8362
Epoch 18/50
395/395 [==============================] - 2s 6ms/step - loss: 2.8462 - mse: 2.8462
Epoch 19/50
395/395 [==============================] - 2s 6ms/step - loss: 2.8309 - mse: 2.8309
Epoch 20/50
395/395 [==============================] - 2s 5ms/step - loss: 2.8255 - mse: 2.8255
Epoch 21/50
395/395 [==============================] - 2s 5ms/step - loss: 2.8197 - mse: 2.8197
Epoch 22/50
395/395 [==============================] - 2s 6ms/step - loss: 2.8087 - mse: 2.8087
Epoch 23/50
395/395 [==============================] - 2s 6ms/step - loss: 2.7888 - mse: 2.7888
Epoch 24/50
395/395 [==============================] - 3s 7ms/step - loss: 2.7806 - mse: 2.7806
Epoch 25/50
395/395 [==============================] - 2s 5ms/step - loss: 2.7862 - mse: 2.7862
Epoch 26/50
395/395 [==============================] - 2s 5ms/step - loss: 2.7818 - mse: 2.7818
Epoch 27/50
395/395 [==============================] - 2s 6ms/step - loss: 2.7529 - mse: 2.7529
Epoch 28/50
395/395 [==============================] - 2s 6ms/step - loss: 2.7657 - mse: 2.7657
Epoch 29/50
395/395 [==============================] - 2s 5ms/step - loss: 2.7498 - mse: 2.7498
Epoch 30/50
395/395 [==============================] - 2s 5ms/step - loss: 2.7575 - mse: 2.7575
Epoch 31/50
395/395 [==============================] - 2s 5ms/step - loss: 2.7587 - mse: 2.7587
Epoch 32/50
395/395 [==============================] - 2s 6ms/step - loss: 2.7400 - mse: 2.7400
Epoch 33/50
395/395 [==============================] - 2s 6ms/step - loss: 2.7605 - mse: 2.7605
Epoch 34/50
395/395 [==============================] - 2s 6ms/step - loss: 2.7310 - mse: 2.7310
Epoch 35/50
395/395 [==============================] - 2s 6ms/step - loss: 2.7163 - mse: 2.7163
Epoch 36/50
395/395 [==============================] - 2s 4ms/step - loss: 2.7127 - mse: 2.7127
Epoch 37/50
395/395 [==============================] - 2s 5ms/step - loss: 2.7274 - mse: 2.7274
Epoch 38/50
395/395 [==============================] - 1s 4ms/step - loss: 2.7094 - mse: 2.7094
Epoch 39/50
395/395 [==============================] - 2s 5ms/step - loss: 2.7162 - mse: 2.7162
Epoch 40/50
395/395 [==============================] - 2s 5ms/step - loss: 2.6941 - mse: 2.6941
Epoch 41/50
395/395 [==============================] - 2s 4ms/step - loss: 2.6859 - mse: 2.6859
Epoch 42/50
395/395 [==============================] - 2s 5ms/step - loss: 2.6946 - mse: 2.6946
Epoch 43/50
395/395 [==============================] - 2s 5ms/step - loss: 2.6817 - mse: 2.6817
Epoch 44/50
395/395 [==============================] - 2s 5ms/step - loss: 2.6823 - mse: 2.6823
Epoch 45/50
395/395 [==============================] - 2s 6ms/step - loss: 2.6638 - mse: 2.6638
Epoch 46/50
395/395 [==============================] - 2s 5ms/step - loss: 2.6708 - mse: 2.6708
Epoch 47/50
395/395 [==============================] - 1s 4ms/step - loss: 2.6746 - mse: 2.6746
Epoch 48/50
395/395 [==============================] - 2s 4ms/step - loss: 2.6706 - mse: 2.6706
Epoch 49/50
395/395 [==============================] - 2s 5ms/step - loss: 2.6469 - mse: 2.6469
Epoch 50/50
395/395 [==============================] - 1s 4ms/step - loss: 2.6557 - mse: 2.6557

In [341]:
pred_val= model.predict(X_test)
r2_score(pred_val, y_test)

132/132 [==============================] - 2s 8ms/step

-9.517014189169657

In [342]:
test = pd.read_csv('../Resultados/df_test.csv')
row_id = test['row_id']
test.drop(['row_id'], axis=1, inplace=True)
test

,competitionId,player_position_1,player_height,player_weight,player_general_var_0,player_general_var_1,player_general_var_2,player_general_var_3,player_general_var_4,player_general_var_5,...,team2_other_ratio_var_47,team2_other_ratio_var_49,team2_other_ratio_var_50,team2_other_ratio_var_51,team2_offensive_derived_var_0,team2_defensive_derived_var_2,team2_offensive_derived_var_11,team2_offensive_derived_var_16,winner_categorical,team_categorical
0,7.0,4.0,0.317073,0.44,0.0,0,0.803922,0.0,0.114754,0.00,...,0.143,0.475,0.437500,0.210526,0.261851,0.410082,0.190509,0.114849,0,0
1,9.0,11.0,0.560976,0.60,0.0,0,0.000000,0.0,0.229508,0.00,...,0.300,0.400,0.354167,0.447368,0.110626,0.480708,0.198072,0.105279,0,0
2,10.0,19.0,0.195122,0.30,0.0,0,0.000000,0.0,0.049180,0.25,...,0.000,0.200,0.312500,0.263158,0.111857,0.566491,0.177065,0.062118,1,1
3,11.0,3.0,0.341463,0.30,0.0,0,0.000000,0.0,0.073770,0.00,...,0.333,0.175,0.395833,0.289474,0.875466,0.365160,0.313902,0.294538,1,0
4,5.0,4.0,0.585366,0.70,0.2,0,0.000000,0.0,0.106557,0.00,...,0.571,0.225,0.479167,0.394737,0.055944,0.445935,0.191068,0.090986,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8769,7.0,11.0,0.463415,0.60,0.0,0,0.000000,0.0,0.065574,0.00,...,1.000,0.275,0.437500,0.342105,0.594270,0.316127,0.290421,0.341016,1,0
8770,4.0,16.0,0.341463,0.40,0.2,0,0.000000,0.0,0.049180,0.00,...,0.000,0.325,0.375000,0.394737,0.162651,0.555421,0.156339,0.087641,0,0
8771,4.0,1.0,0.439024,0.36,0.0,0,0.000000,0.0,0.040984,0.00,...,0.125,0.200,0.083333,0.447368,0.128139,0.444911,0.182449,0.094133,1,1
8772,10.0,1.0,0.463415,0.54,0.0,0,0.000000,0.0,0.016393,0.00,...,0.500,0.600,0.416667,0.184211,0.036835,0.781462,0.141524,0.045464,2,0
8773,4.0,3.0,0.560976,0.48,0.0,0,0.774510,0.0,0.032787,0.00,...,0.100,0.375,0.479167,0.184211,0.146340,0.522738,0.174473,0.113514,2,0

In [343]:
pred = model.predict(test)
pred.shape

275/275 [==============================] - 1s 4ms/step

(8774, 1)

In [344]:
submission = pd.DataFrame()
submission['row_id'] = row_id
submission['rating_num'] = pred
submission

      row_id  rating_num
0      14785    7.317868
1      15125    7.408456
2      13095    7.098206
3       6079    7.325719
4      16584    7.346348
...      ...         ...
8769   21259    7.162840
8770    9371    7.494697
8771   23226    7.151408
8772   26623    8.026842
8773   13814    7.405138

[8774 rows x 2 columns]

In [345]:
submission.to_csv('../Resultados/submission-8.csv', index=False)